# Generated by Django 4.2 on 2025-11-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('money', models.FloatField(default=5000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('freshness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('freshness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('freshness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.malt')),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.yeast')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('status', models.CharField(choices=[('mash', 'Mash'), ('fermenting', 'Fermenting'), ('ready', 'Ready')], max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.recipe')),
            ],
        ),
    ]
