# Generated by Django 5.2.8 on 2025-11-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('hop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.hop')),
            ],
        ),
        migrations.CreateModel(
            name='MaltInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.malt')),
            ],
        ),
        migrations.CreateModel(
            name='YeastInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.yeast')),
            ],
        ),
    ]
