# Generated by Django 5.2.8 on 2025-11-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_hopinventory_maltinventory_yeastinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopinventory',
            name='freshness',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='maltinventory',
            name='freshness',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='yeastinventory',
            name='freshness',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
