# Generated by Django 5.2.8 on 2025-11-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_hopinventory_freshness_maltinventory_freshness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitterSmell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaltColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaltTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Smell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YeastTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hop',
            name='freshness',
        ),
        migrations.RemoveField(
            model_name='malt',
            name='freshness',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='freshness',
        ),
        migrations.AddField(
            model_name='hop',
            name='a_acid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hop',
            name='b_acid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='malt',
            name='bitter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malt',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='fermentability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='sedimentability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='temp_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='temp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hop',
            name='bitter_or_smell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.bittersmell'),
        ),
        migrations.AddField(
            model_name='malt',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.maltcolor'),
        ),
        migrations.AddField(
            model_name='malt',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.malttaste'),
        ),
        migrations.AddField(
            model_name='hop',
            name='smell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.smell'),
        ),
        migrations.AddField(
            model_name='yeast',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beer.yeasttaste'),
        ),
    ]
