# Generated by Django 5.2.8 on 2025-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_bittersmell_maltcolor_malttaste_smell_yeasttaste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop',
            name='a_acid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hop',
            name='b_acid',
            field=models.FloatField(default=0),
        ),
    ]
