# Generated by Django 5.2.8 on 2025-11-25 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0006_hopinventory_user_maltinventory_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='current_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='money',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
