# Generated by Django 5.2.8 on 2025-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_gamestate_user_alter_gamestate_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malt',
            name='color',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MaltColor',
        ),
    ]
