# Generated by Django 5.2.8 on 2025-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0009_brewer_containertype_mill_tank_hop_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewer',
            name='img',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='container',
            name='img',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mill',
            name='img',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tank',
            name='img',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
