# Generated by Django 5.2.8 on 2025-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0011_brewerinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewerinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
